// Regression tests for backend/utils/capacityAggregates.js (Phase DOC-07).
// Pure, dependency-free — no MongoDB required, matching slotEngine.test.mjs.
import assert from "assert";
import { buildDayCapacity, dayHasAvailability } from "../utils/capacityAggregates.js";

// 1. Basic day: 09:00-11:00, 30min slots, no buffer/breaks -> 4 theoretical
// slots, one booked, rest available.
let day = buildDayCapacity({
  dayConfig: { dayOfWeek: "monday", startTime: "09:00", endTime: "11:00", slotDurationMinutes: 30, bufferMinutes: 0 },
  appointments: [{ timeSlot: "09:00-09:30", status: "approved", appointmentId: "a1", patientName: "Asha" }],
});
assert.strictEqual(day.capacity.totalSlots, 4);
assert.strictEqual(day.capacity.booked, 1);
assert.strictEqual(day.capacity.available, 3);
assert.strictEqual(day.capacity.utilizationPercent, 25);
assert.strictEqual(day.timeline[0].status, "booked");
assert.strictEqual(day.timeline[0].appointment.patientName, "Asha");
assert.strictEqual(day.timeline[1].status, "available");
assert.strictEqual(day.nextFreeSlotToday, "09:30-10:00");
console.log("PASS: basic day capacity + next free slot");

// 2. Break exclusion — a break slot must show as "break", not "available".
day = buildDayCapacity({
  dayConfig: {
    dayOfWeek: "monday",
    startTime: "09:00",
    endTime: "11:00",
    slotDurationMinutes: 30,
    bufferMinutes: 0,
    breaks: [{ start: "09:30", end: "10:00" }],
  },
  appointments: [],
});
const breakSlot = day.timeline.find((t) => t.slot === "09:30-10:00");
assert.strictEqual(breakSlot, undefined, "a slot fully inside a break should never be generated by slotEngine at all");
assert.strictEqual(day.capacity.totalSlots, 3);
console.log("PASS: break correctly removed from generated slots");

// 3. Not a working day -> unavailableReason set, empty timeline, no fake numbers.
day = buildDayCapacity({ dayConfig: null, appointments: [] });
assert.strictEqual(day.unavailableReason, "not_a_working_day");
assert.strictEqual(day.timeline.length, 0);
assert.strictEqual(day.capacity.totalSlots, 0);
assert.strictEqual(day.capacity.utilizationPercent, null, "utilization must be null (not 0 or fabricated) when there are no slots to divide by");
console.log("PASS: non-working day reports real unavailability, never fake zero-capacity numbers");

// 4. Blocked date takes priority reporting over a working-day config.
day = buildDayCapacity({
  dayConfig: { dayOfWeek: "monday", startTime: "09:00", endTime: "10:00", slotDurationMinutes: 30 },
  appointments: [],
  blockedReason: "Clinic closed for maintenance",
});
assert.strictEqual(day.unavailableReason, "blocked_date");
assert.strictEqual(day.timeline.every((t) => t.status === "blocked"), true);
console.log("PASS: blocked date reason surfaces and every slot is marked blocked");

// 5. Approved leave.
day = buildDayCapacity({
  dayConfig: { dayOfWeek: "monday", startTime: "09:00", endTime: "10:00", slotDurationMinutes: 30 },
  appointments: [],
  leaveReason: "Medical conference",
});
assert.strictEqual(day.unavailableReason, "on_leave");
assert.strictEqual(day.timeline.every((t) => t.status === "leave"), true);
console.log("PASS: approved leave reason surfaces and every slot is marked leave");

// 6. Double-booking conflict detection — two ACTIVE appointments landing on
// the same slot (legacy data / pre-unique-index race) must be flagged, not
// silently hidden or silently merged.
day = buildDayCapacity({
  dayConfig: { dayOfWeek: "monday", startTime: "09:00", endTime: "10:00", slotDurationMinutes: 30 },
  appointments: [
    { timeSlot: "09:00-09:30", status: "approved", appointmentId: "a1", patientName: "Asha" },
    { timeSlot: "09:00-09:30", status: "pending", appointmentId: "a2", patientName: "Bala" },
  ],
});
assert.strictEqual(day.conflicts.doubleBookedSlots.length, 1);
assert.strictEqual(day.conflicts.doubleBookedSlots[0], "09:00-09:30");
assert.strictEqual(day.timeline[0].isConflict, true);
assert.strictEqual(day.timeline[0].overflowCount, 1);
console.log("PASS: double-booked slot flagged as a real conflict");

// 7. Appointment outside currently-configured hours (doctor shrank working
// hours after this was booked) -> must appear in outsideCurrentHours, not
// silently disappear from the schedule.
day = buildDayCapacity({
  dayConfig: { dayOfWeek: "monday", startTime: "09:00", endTime: "10:00", slotDurationMinutes: 30 },
  appointments: [{ timeSlot: "16:00-16:30", status: "approved", appointmentId: "a3", patientName: "Chen" }],
});
assert.strictEqual(day.conflicts.outsideCurrentHours.length, 1);
assert.strictEqual(day.conflicts.outsideCurrentHours[0].patientName, "Chen");
console.log("PASS: appointment outside newly-edited working hours flagged as a conflict");

// 8. Cancelled appointments must not occupy a slot as "booked" (the slot is
// truly free again). Completed/review_eligible are, per this codebase's own
// ACTIVE_STATUSES definition, still real historical occupants of their
// slot (the visit happened) — they correctly still show as "booked", not
// "available". Both must still be counted in their own real buckets.
day = buildDayCapacity({
  dayConfig: { dayOfWeek: "monday", startTime: "09:00", endTime: "10:00", slotDurationMinutes: 30 },
  appointments: [
    { timeSlot: "09:00-09:30", status: "cancelled", appointmentId: "a4", patientName: "Dev" },
    { timeSlot: "09:30-10:00", status: "review_eligible", appointmentId: "a5", patientName: "Esha" },
  ],
});
assert.strictEqual(day.timeline[0].status, "available", "a cancelled appointment must free up its slot");
assert.strictEqual(day.timeline[1].status, "booked", "review_eligible is a completed-visit state and still occupied that slot historically");
assert.strictEqual(day.capacity.cancelled, 1);
assert.strictEqual(day.capacity.completed, 1);
console.log("PASS: cancelled appointments free their slot; completed-visit statuses correctly remain booked");

// 9. dayHasAvailability helper.
assert.strictEqual(dayHasAvailability({ capacity: { available: 2 } }), true);
assert.strictEqual(dayHasAvailability({ capacity: { available: 0 } }), false);
assert.strictEqual(dayHasAvailability(null), false);
console.log("PASS: dayHasAvailability helper");



// 10. Today's past slots must be excluded while future slots remain bookable.
// `currentTimeMinutes` follows the application's UTC business-date convention.
day = buildDayCapacity({
  dayConfig: { dayOfWeek: "monday", startTime: "09:00", endTime: "12:00", slotDurationMinutes: 60, bufferMinutes: 0 },
  appointments: [],
  currentTimeMinutes: 10 * 60 + 30,
});
assert.strictEqual(day.timeline.find((t) => t.slot === "09:00-10:00").status, "past");
assert.strictEqual(day.timeline.find((t) => t.slot === "10:00-11:00").status, "past");
assert.strictEqual(day.timeline.find((t) => t.slot === "11:00-12:00").status, "available");
assert.strictEqual(dayHasAvailability(day), true);
console.log("PASS: today's past slots are excluded while future slots remain available");

// 11. A booked future slot remains booked; it is not confused with past-time filtering.
day = buildDayCapacity({
  dayConfig: { dayOfWeek: "monday", startTime: "09:00", endTime: "12:00", slotDurationMinutes: 60, bufferMinutes: 0 },
  appointments: [{ timeSlot: "11:00-12:00", status: "approved", appointmentId: "a6" }],
  currentTimeMinutes: 10 * 60 + 30,
});
assert.strictEqual(day.timeline.find((t) => t.slot === "11:00-12:00").status, "booked");
console.log("PASS: future booked slot remains unavailable");

console.log("ALL CAPACITY AGGREGATES TESTS PASSED");
