import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../..");
const read = (file) => fs.readFileSync(path.join(root, file), "utf8");
const contact = read("src/pages/public/Contact.jsx");
const adminPage = read("src/pages/admin/AdminLeads.jsx");
const controller = read("backend/controllers/leadController.js");
const model = read("backend/models/Lead.js");
const routes = read("backend/routes/leadRoutes.js");
const email = read("backend/services/emailService.js");
const app = read("backend/app.js");
const notifications = read("backend/models/NotificationDelivery.js");
const realtimeEmitter = read("backend/realtime/notificationEmitter.js");
const realtimeCenter = read("src/components/realtime/LiveNotificationCenter.jsx");

assert.match(contact, /leadApi\.create\(form\)/);
assert.match(contact, /response\?\.success/);
assert.match(contact, /response\?\.data\?\.referenceId/);
assert.match(contact, /\/privacy-policy/);
assert.match(contact, /\/data-rights/);
assert.match(contact, /consent/);
assert.match(contact, /disabled=\{state\.loading\}/);
assert.doesNotMatch(contact, /submissionUnavailable/);
assert.doesNotMatch(contact, /localStorage/);
assert.doesNotMatch(contact, /sessionStorage/);
assert.match(adminPage, /leadApi\.list/);
assert.match(adminPage, /leadApi\.assign/);
assert.match(adminPage, /leadApi\.priority/);
assert.match(adminPage, /leadApi\.status/);
assert.match(adminPage, /leadApi\.note/);
assert.match(adminPage, /rowKey="id"/);
assert.match(controller, /req\.user\?\._id \|\| null/);
assert.match(controller, /submissionFingerprint/);
assert.match(controller, /crypto\.randomBytes/);
assert.match(controller, /res\.status\(201\)/);
assert.match(controller, /sendContactLeadAcknowledgement/);
assert.match(controller, /notificationStatus/);
assert.match(controller, /notificationEmitter\.emitToAdmins/);
assert.match(controller, /eventKey: `lead_created:/);
assert.match(controller, /metadata: \{[\s\S]*action: \{ to: "\/admin\/leads" \}/);
assert.match(controller, /writeAdminLog/);
assert.match(controller, /transitions/);
assert.match(controller, /privacyPolicyVersion/);
assert.match(controller, /termsVersion/);
assert.match(controller, /consentedAt/);
assert.doesNotMatch(controller, /req\.body\.userId/);
assert.doesNotMatch(controller, /dangerouslySetInnerHTML/);
assert.match(model, /publicId: \{ type: String, required: true, unique: true, index: true \}/);
assert.match(model, /LEAD_STATUSES/);
assert.match(model, /LEAD_PRIORITIES/);
assert.match(model, /notes/);
assert.match(model, /timeline/);
assert.match(routes, /router\.post\("\/", publicLeadLimiter, optionalProtect, createLead\)/);
assert.match(routes, /router\.use\(protect, requireAdmin, adminLeadLimiter\)/);
assert.match(routes, /router\.post\("\/:id\/notes"/);
assert.match(email, /BREVO_ENDPOINT/);
assert.match(email, /sendContactLeadAcknowledgement/);
assert.match(notifications, /"lead"/);
assert.match(realtimeEmitter, /emitToAdmins/);
assert.match(realtimeCenter, /notification\.metadata\?\.action\?\.to/);
assert.match(realtimeCenter, /navigate\(target\)/);
assert.doesNotMatch(controller, /nodemailer|smtp:|SMTP_HOST|SMTP_PASSWORD/);
assert.doesNotMatch(routes, /nodemailer|smtp:|SMTP_HOST|SMTP_PASSWORD/);
assert.doesNotMatch(contact, /nodemailer|smtp:|SMTP_HOST|SMTP_PASSWORD/);
assert.match(app, /app\.use\("\/api\/leads", leadRoutes\)/);
console.log("P17 lead contract PASS");
