import { Router } from "express";
import { archiveService, createService, deleteService, getService, getServiceCategories, getServiceStats, listServices, publishService, updateService } from "../../controllers/admin/serviceAdminController.js";
import { protect } from "../../middleware/authMiddleware.js";
import { requireAdmin, requirePermission } from "../../middleware/adminMiddleware.js";
const router = Router();
router.use(protect, requireAdmin);
router.get("/categories", getServiceCategories);
router.get("/stats", getServiceStats);
router.get("/", listServices);
router.get("/:id", getService);
router.post("/", requirePermission("manage_services"), createService);
router.put("/:id", requirePermission("manage_services"), updateService);
router.post("/:id/publish", requirePermission("manage_services"), publishService);
router.post("/:id/archive", requirePermission("manage_services"), archiveService);
router.delete("/:id", requirePermission("manage_services"), deleteService);
export default router;
