// Shared navigation catalog — the single source of truth for every role's
// nav items. Previously this list lived only inside Sidebar.jsx; extracted
// here so the new global Command Palette (Cmd/Ctrl+K search) can reuse the
// exact same paths/icons/roles instead of maintaining a second copy that
// would inevitably drift out of sync with the sidebar.
//
// `group` was added for the sidebar information-architecture rebuild —
// every existing route keeps its existing path/roles/icon; this only adds
// a grouping label so the sidebar can render section headers instead of
// one flat list. Groups are role-specific because admin/doctor/patient
// navigate genuinely different concepts:
//   admin:   Overview, Operations, Clinical, Finance, Intelligence, Administration
//   doctor:  Overview, Clinical, Practice, Finance, Intelligence, Administration
//   patient: Overview, Care, Finance, Intelligence, Account
// `primary: true` marks the handful of destinations that should carry
// stronger visual weight than the rest of their group (per the sidebar UX
// requirement that not every item is visually equal).
import {
  Activity,
  CalendarDays,
  CreditCard,
  FileText,
  HeartPulse,
  History,
  Inbox,
  Sparkles,
  LayoutDashboard,
  LayoutGrid,
  LineChart,
  ListChecks,
  Zap,
  NotebookPen,
  Radar,
  ShieldCheck,
  Settings,
  Stethoscope,
  Users,
  Star,
  WalletCards,
  Briefcase,
  Workflow,
  Gauge,
  Bot,
  GitBranch,
  Compass,
  ClipboardCheck,
  Plug,
  UserCog,
  Lock,
  ToggleLeft,
  Download,
} from "lucide-react";

export const GROUP_ORDER = [
  "Overview",
  "Operations",
  "Clinical",
  "Care",
  "Practice",
  "Finance",
  "Intelligence",
  "Administration",
  "Account",
];

export const buildNavigation = (t) => [
  { name: t("sidebar.dashboard"), path: "/admin/dashboard", icon: LayoutDashboard, roles: ["admin", "super_admin"], group: "Overview", primary: true },
  { name: "Mission Control", path: "/admin/mission-control", icon: Radar, roles: ["admin", "super_admin"], group: "Overview" },
  { name: "Platform Health", path: "/admin/platform-health", icon: HeartPulse, roles: ["admin", "super_admin"], group: "Overview" },
  { name: "Operations Center", path: "/admin/operations-center", icon: ListChecks, roles: ["admin", "super_admin"], group: "Operations" },
  { name: "Operations Command Workspace", path: "/admin/operations-command-workspace", icon: Compass, roles: ["admin", "super_admin"], group: "Operations", primary: true },
  { name: "Workflow Engine", path: "/admin/workflow-engine", icon: Workflow, roles: ["admin", "super_admin"], group: "Operations" },
  { name: "Smart Assignment", path: "/admin/smart-assignment", icon: Gauge, roles: ["admin", "super_admin"], group: "Operations" },
  { name: "Monitoring Platform", path: "/admin/monitoring", icon: Activity, roles: ["admin", "super_admin"], group: "Operations" },
  { name: "Automation Studio", path: "/admin/automation-studio", icon: Bot, roles: ["admin", "super_admin"], group: "Operations" },
  { name: "Workflow Intelligence", path: "/admin/workflow-intelligence", icon: Sparkles, roles: ["admin", "super_admin"], group: "Operations" },
  { name: "Integration Hub", path: "/admin/integration-hub", icon: Plug, roles: ["admin", "super_admin"], group: "Operations" },
  { name: "Process Command Center", path: "/admin/process-command-center", icon: Compass, roles: ["admin", "super_admin"], group: "Operations", primary: true },
  { name: "Process Orchestrator", path: "/admin/process-orchestrator", icon: GitBranch, roles: ["admin", "super_admin"], group: "Operations" },
  { name: "Process Designer", path: "/admin/process-designer", icon: GitBranch, roles: ["admin", "super_admin"], group: "Operations" },
  { name: "Process Analytics", path: "/admin/process-analytics", icon: LineChart, roles: ["admin", "super_admin"], group: "Operations" },
  { name: "Process Governance", path: "/admin/process-governance", icon: ClipboardCheck, roles: ["admin", "super_admin"], group: "Operations" },
  { name: "Smart Widgets", path: "/admin/widgets", icon: LayoutGrid, roles: ["admin", "super_admin"], group: "Intelligence" },
  { name: "Executive Actions", path: "/admin/executive-actions", icon: Zap, roles: ["admin", "super_admin"], group: "Administration" },
  { name: t("sidebar.dashboard"), path: "/doctor/dashboard", icon: LayoutDashboard, roles: ["doctor"], group: "Overview", primary: true },
  { name: "Smart Inbox", path: "/doctor/inbox", icon: Inbox, roles: ["doctor"], group: "Overview" },
  { name: t("sidebar.dashboard"), path: "/patient/dashboard", icon: LayoutDashboard, roles: ["patient"], group: "Overview", primary: true },
  { name: t("sidebar.services"), path: "/admin/services", icon: Settings, roles: ["admin", "super_admin"], group: "Clinical" },
  { name: t("p19.articles.title"), path: "/admin/articles", icon: FileText, roles: ["admin", "super_admin"], group: "Administration" },
  { name: t("sidebar.doctors"), path: "/admin/doctors", icon: Stethoscope, roles: ["admin", "super_admin"], group: "Clinical" },
  { name: t("sidebar.doctors"), path: "/patient/doctors", icon: Stethoscope, roles: ["patient"], group: "Care" },
  { name: "Saved Doctors", path: "/patient/saved-doctors", icon: Stethoscope, roles: ["patient"], group: "Care" },
  { name: t("sidebar.patients"), path: "/admin/patients", icon: Users, roles: ["admin", "super_admin"], group: "Clinical" },
  { name: t("sidebar.patients"), path: "/doctor/patients", icon: Users, roles: ["doctor"], group: "Clinical" },
  { name: t("sidebar.appointments"), path: "/admin/appointments", icon: CalendarDays, roles: ["admin", "super_admin"], group: "Clinical" },
  { name: t("sidebar.appointments"), path: "/doctor/appointments", icon: CalendarDays, roles: ["doctor"], group: "Clinical" },
  { name: "Business Overview", path: "/doctor/business", icon: Briefcase, roles: ["doctor"], group: "Intelligence" },
  { name: t("sidebar.reviews"), path: "/doctor/reviews", icon: Star, roles: ["doctor"], group: "Clinical" },
  { name: t("sidebar.reviews"), path: "/admin/reviews", icon: Star, roles: ["admin", "super_admin"], group: "Clinical" },
  { name: t("p17.adminLeads.title"), path: "/admin/leads", icon: Inbox, roles: ["admin", "super_admin"], group: "Operations" },
  { name: t("sidebar.earnings"), path: "/doctor/earnings", icon: WalletCards, roles: ["doctor"], group: "Finance" },
  { name: t("sidebar.appointments"), path: "/patient/appointments", icon: CalendarDays, roles: ["patient"], group: "Care", primary: true },
  { name: t("sidebar.clinical"), path: "/doctor/clinical", icon: NotebookPen, roles: ["doctor"], group: "Clinical" },
  { name: t("sidebar.schedule"), path: "/doctor/schedule", icon: CalendarDays, roles: ["doctor"], group: "Clinical" },
  { name: t("sidebar.documents"), path: "/doctor/documents", icon: FileText, roles: ["doctor"], group: "Clinical" },
  { name: t("sidebar.analytics"), path: "/doctor/analytics", icon: LineChart, roles: ["doctor"], group: "Intelligence" },
  { name: t("sidebar.reputation"), path: "/doctor/reputation", icon: Star, roles: ["doctor"], group: "Intelligence" },
  { name: t("p18.commandCenterTitle"), path: "/doctor/profile-strength", icon: LineChart, roles: ["doctor"], group: "Intelligence", primary: true },
  { name: "Professional Profile", path: "/doctor/profile/edit", icon: UserCog, roles: ["doctor"], group: "Practice" },
  { name: "Practice", path: "/doctor/practice", icon: ShieldCheck, roles: ["doctor"], group: "Practice" },
  { name: "Verification", path: "/doctor/verification", icon: ShieldCheck, roles: ["doctor"], group: "Administration" },
  { name: "Subscription", path: "/doctor/billing", icon: CreditCard, roles: ["doctor"], group: "Finance" },
  { name: "Practice Settings", path: "/doctor/practice-settings", icon: Settings, roles: ["doctor"], group: "Administration" },
  { name: t("sidebar.payments"), path: "/admin/payments", icon: CreditCard, roles: ["admin", "super_admin"], group: "Finance" },
  { name: t("sidebar.refunds"), path: "/admin/refunds", icon: CreditCard, roles: ["admin", "super_admin"], group: "Finance" },
  { name: "Withdrawals", path: "/admin/withdrawals", icon: CreditCard, roles: ["admin", "super_admin"], group: "Finance" },
  { name: t("sidebar.payments"), path: "/patient/payments", icon: CreditCard, roles: ["patient"], group: "Finance" },
  { name: t("sidebar.finance"), path: "/admin/finance", icon: CreditCard, roles: ["admin", "super_admin"], group: "Finance" },
  { name: "Finance Ops", path: "/admin/finance/ops", icon: LineChart, roles: ["admin", "super_admin"], group: "Finance" },
  { name: "AI Command", path: "/admin/ai", icon: Sparkles, roles: ["admin", "super_admin"], group: "Intelligence" },
  { name: "Invoices", path: "/admin/invoices", icon: FileText, roles: ["admin", "super_admin"], group: "Finance" },
  { name: t("sidebar.wallet"), path: "/patient/wallet", icon: CreditCard, roles: ["patient"], group: "Finance" },
  { name: "AI Assistant", path: "/patient/ai", icon: Sparkles, roles: ["patient"], group: "Intelligence" },
  { name: "Invoices", path: "/patient/invoices", icon: FileText, roles: ["patient"], group: "Finance" },
  { name: t("sidebar.records"), path: "/patient/records", icon: FileText, roles: ["patient"], group: "Care" },
  { name: t("sidebar.family"), path: "/patient/family", icon: Users, roles: ["patient"], group: "Account" },
  { name: t("sidebar.insurance"), path: "/patient/insurance", icon: ShieldCheck, roles: ["patient"], group: "Finance" },
  { name: "Health Profile", path: "/patient/profile", icon: HeartPulse, roles: ["patient"], group: "Account" },
  { name: "Health Journey", path: "/patient/journey", icon: History, roles: ["patient"], group: "Care" },
  { name: t("sidebar.settings"), path: "/admin/settings", icon: Settings, roles: ["admin", "super_admin"], group: "Administration" },
  { name: "User Management", path: "/admin/user-management", icon: UserCog, roles: ["admin", "super_admin"], group: "Administration" },
  { name: "Access Control", path: "/admin/access-control", icon: Lock, roles: ["admin", "super_admin"], group: "Administration" },
  { name: "Feature Management", path: "/admin/feature-management", icon: ToggleLeft, roles: ["admin", "super_admin"], group: "Administration" },
  { name: "Export Center", path: "/admin/export-center", icon: Download, roles: ["admin", "super_admin"], group: "Administration" },
  { name: "Audit Center", path: "/admin/audit", icon: LineChart, roles: ["admin", "super_admin"], group: "Administration" },
  { name: "Notifications", path: "/admin/notifications", icon: Activity, roles: ["admin", "super_admin"], group: "Administration" },
  { name: "Analytics", path: "/admin/analytics", icon: LineChart, roles: ["admin", "super_admin"], group: "Intelligence" },
  { name: "CMS", path: "/admin/cms", icon: FileText, roles: ["admin", "super_admin"], group: "Administration" },
];
