export default {
  home: {
    verifiedDoctors: "सत्यापित डॉक्टर", completedConsultations: "पूरी हुई कंसल्टेशन", specializations: "विशेषज्ञताएँ", citiesCovered: "कवर किए गए शहर",
    howBookingWorks: "बुकिंग वास्तव में कैसे होती है?", howBookingWorksAnswer: "सत्यापित डॉक्टर खोजें, प्रोफाइल और वास्तविक उपलब्धता देखें, स्लॉट का अनुरोध करें और स्वीकृति के बाद भुगतान पूरा करें।",
    verifiedBadge: "सत्यापित बैज का क्या मतलब है?", verifiedBadgeAnswer: "पब्लिक डायरेक्टरी केवल सक्रिय, सत्यापित और स्वीकृत डॉक्टर प्रोफाइल दिखाती है।",
    availabilityQuestion: "क्या उपलब्धता वास्तविक है?", availabilityAnswer: "डॉक्टर की उपलब्धता उसी शेड्यूलिंग डेटा से आती है जो बुकिंग में उपयोग होता है।",
    reviewsQuestion: "क्या कोई भी रिव्यू दे सकता है?", reviewsAnswer: "रिव्यू पूरी हुई कंसल्टेशन गतिविधि से जुड़े होते हैं।",
    privacyQuestion: "पब्लिक में क्या दिखाई देता है?", privacyAnswer: "केवल सुरक्षित प्रोफेशनल प्रोफाइल जानकारी दिखाई जाती है। निजी मरीज डेटा और दस्तावेज़ ऑथेंटिकेशन के पीछे रहते हैं।",
    doctor: "डॉक्टर", reviews: "रिव्यू", online: "ऑनलाइन", offline: "क्लिनिक में", homeVisit: "होम विज़िट", patient: "MediCore मरीज",
    yearsExperience: "{{count}} वर्षों का अनुभव", reviewCount: "{{count}} रिव्यू", specialtyDoctors: "{{count}} सत्यापित डॉक्टर", averageRating: "{{rating}} औसत रेटिंग", verifiedPatientExperience: "सत्यापित मरीज अनुभव", patientExperienceFallback: "MediCore के माध्यम से साझा किया गया मरीज अनुभव।", consultedDoctor: "{{name}} से कंसल्ट किया",
    journey: { discover: "खोजें", discoverText: "स्पेशलिटी, लोकेशन, मोड और उपलब्धता के आधार पर डॉक्टर खोजें।", verify: "सत्यापित करें", verifyText: "क्रेडेंशियल्स, अनुभव, रिव्यू और प्रैक्टिस विवरण देखें।", book: "बुक करें", bookText: "डॉक्टर के शेड्यूल से वास्तविक स्लॉट का अनुरोध करें।", consult: "कंसल्ट करें", consultText: "अपॉइंटमेंट और क्लिनिकल वर्कफ़्लो में आगे बढ़ें।", continue: "जारी रखें", continueText: "फॉलो-अप, रिव्यू और केयर हिस्ट्री जुड़ी रहती है।" },
    trustCards: { verifiedIdentity: "सत्यापित पहचान", verifiedIdentityText: "केवल स्वीकृत डॉक्टर प्रोफाइल", realScheduling: "वास्तविक शेड्यूलिंग", realSchedulingText: "बुकिंग इंजन से उपलब्धता", consultationReviews: "कंसल्टेशन रिव्यू", consultationReviewsText: "पूरी हुई देखभाल से जुड़े", privateRecords: "निजी रिकॉर्ड", privateRecordsText: "क्लिनिकल डेटा सुरक्षित रहता है", paymentExpectations: "भुगतान की अपेक्षाएँ स्पष्ट हैं", paymentExpectationsText: "करेंसी, टैक्स, बुकिंग विंडो और रिफंड कॉन्फ़िगरेशन अस्पताल सेटिंग्स से आते हैं।", professionalDepth: "प्रोफेशनल जानकारी की गहराई", professionalDepthText: "शिक्षा, अनुभव, पुरस्कार, प्रकाशन, क्लिनिक और भाषाएँ निजी रिकॉर्ड उजागर किए बिना प्रोफाइल को बेहतर बनाते हैं।", boundedIntelligence: "इंटेलिजेंस की सीमा स्पष्ट है", boundedIntelligenceText: "डिसीजन-सपोर्ट शॉर्टकट मरीजों को स्पेशलिटी समझने में मदद करते हैं, लेकिन लक्षणों का निदान करने का दावा नहीं करते।" }
  },
  search: { highestRated: "सबसे अधिक रेटेड", mostExperienced: "सबसे अनुभवी", lowestFees: "सबसे कम फीस", highestFees: "सबसे अधिक फीस", mostReviewed: "सबसे अधिक रिव्यू", recentlyVerified: "हाल ही में सत्यापित", removeSaved: "सेव किए डॉक्टर से हटाएँ", saveDoctor: "डॉक्टर सेव करें", yearsShort: "वर्ष", pageOf: "पेज {{page}} / {{pages}}" },
  profile: { online: "ऑनलाइन", offline: "क्लिनिक में", homeVisit: "होम विज़िट", doctorUnavailable: "डॉक्टर उपलब्ध नहीं है", rating: "रेटिंग", reviews: "रिव्यू", consultations: "कंसल्टेशन", years: "वर्ष", primaryPractice: "मुख्य प्रैक्टिस", locationNotSpecified: "लोकेशन उपलब्ध नहीं", patientReviews: "मरीज रिव्यू · {{count}}", basedOnReviews: "{{count}} सार्वजनिक रिव्यू के आधार पर", loading: "लोड हो रहा है…", next: "अगला", languages: "भाषाएँ", insurance: "सूचीबद्ध इंश्योरेंस", emergency: "इमरजेंसी", medicalCouncil: "मेडिकल काउंसिल", present: "वर्तमान", minutes: "मिनट", days: { monday: "सोमवार", tuesday: "मंगलवार", wednesday: "बुधवार", thursday: "गुरुवार", friday: "शुक्रवार", saturday: "शनिवार", sunday: "रविवार" }, yes: "हाँ", no: "नहीं", bookingWindow: "बुकिंग विंडो: उपलब्धता के अनुसार {{days}} दिनों तक।", currencyTax: "करेंसी: {{currency}}; कॉन्फ़िगर टैक्स दर: {{taxRate}}%।" },
  compare: { specialization: "विशेषज्ञता", qualification: "योग्यता", experience: "अनुभव", years: "{{count}} वर्ष", practiceLocation: "प्रैक्टिस लोकेशन", hospitalClinic: "अस्पताल / क्लिनिक", languages: "भाषाएँ", consultationModes: "कंसल्टेशन मोड", consultationFee: "कंसल्टेशन फीस", rating: "रेटिंग", ratingValue: "{{value}} / 5", reviews: "रिव्यू", completedConsultations: "पूरी हुई कंसल्टेशन", notAvailable: "—" },
  contact: { email: "ईमेल", phone: "फोन", timezone: "ऑपरेटिंग टाइमज़ोन", notConfigured: "सार्वजनिक रूप से कॉन्फ़िगर नहीं" },
  about: { discover: "खोजें", discoverText: "डॉक्टर सर्च, स्पेशलिटी ब्राउज़िंग और लोकेशन फ़िल्टर।", trust: "विश्वास", trustDescription: "बुकिंग से पहले सत्यापन, प्रोफेशनल जानकारी, रिव्यू और प्रैक्टिस संदर्भ।", coordinate: "समन्वय", coordinateText: "उपलब्धता और अपॉइंटमेंट अनुरोध एक ही वर्कफ़्लो से जुड़े हैं।", care: "देखभाल", careText: "कंसल्टेशन और समर्थित क्लिनिकल वर्कफ़्लो पब्लिक सीमा के पीछे जारी रहते हैं।", continuity: "निरंतरता", continuityText: "कंसल्टेशन के बाद फॉलो-अप शेड्यूलिंग और मरीज वर्कफ़्लो जारी रहते हैं।", patient1: "बुकिंग से पहले डॉक्टरों की तुलना करें", patient2: "सत्यापित प्रोफेशनल जानकारी देखें", patient3: "वास्तविक उपलब्धता से फ़िल्टर करें", patient4: "फीस और रिफंड अपेक्षाएँ समझें", patient5: "पेशेंट रिकॉर्ड्स तक आगे बढ़ें", patient6: "फॉलो-अप इतिहास से जुड़े रहें", platform1: "विस्तृत प्रोफेशनल प्रोफाइल", platform2: "सत्यापन और अनुपालन स्थिति", platform3: "पब्लिक प्रतिष्ठा और रिव्यू", platform4: "उपलब्धता और बुकिंग", platform5: "प्रैक्टिस और मरीज वर्कफ़्लो", platform6: "कंसल्टेशन के बाद फॉलो-अप", trustTitle: "बुकिंग से पहले विश्वास", trustText: "सत्यापन, रिव्यू इतिहास, प्रोफेशनल विवरण और उपलब्धता बुकिंग से पहले दिखाई जाती है।", sourceTitle: "एक ही विश्वसनीय स्रोत", sourceText: "पब्लिक डिस्कवरी वही डॉक्टर, अपॉइंटमेंट, रिव्यू और अस्पताल कॉन्फ़िगरेशन डेटा पढ़ती है जो आंतरिक वर्कफ़्लो चलाता है।", continuityTitle: "क्लिक के बाद निरंतरता", continuityWorkflowText: "पब्लिक यात्रा समर्थित अपॉइंटमेंट, कंसल्टेशन और फॉलो-अप वर्कफ़्लो से जुड़ती है।" },
  services: { price: "कीमत", explore: "सेवा देखें", published: "प्रकाशित", noServices: "अभी कोई सेवा सार्वजनिक रूप से उपलब्ध नहीं है।", count: "{{count}} सेवाएँ एक्सप्लोर करने के लिए तैयार हैं" },
  articles: { published: "प्रकाशित", count: "लेख", read: "लेख पढ़ें", noArticles: "आपकी खोज से कोई प्रकाशित लेख नहीं मिला।" },
  articleDetail: { published: "प्रकाशित" }
};
