export default {
  home: {
    verifiedDoctors: "Verified doctors", completedConsultations: "Completed consultations", specializations: "Specializations", citiesCovered: "Cities covered",
    howBookingWorks: "How does booking actually work?", howBookingWorksAnswer: "Search a verified doctor, review the profile and real availability, request a slot, then complete payment after approval. The same appointment record continues into the patient dashboard and clinical workflow.",
    verifiedBadge: "What does the verified badge mean?", verifiedBadgeAnswer: "The public directory only exposes doctors whose profile is active, verified and approved. Verification state is sourced from the doctor record rather than a marketing label.",
    availabilityQuestion: "Is availability real?", availabilityAnswer: "Doctor availability comes from the scheduling data used by the booking workflow. The discovery layer does not invent appointment times.",
    reviewsQuestion: "Can anyone leave a review?", reviewsAnswer: "Reviews are tied to completed consultation activity in MediCore. Public review data is filtered for admin-deleted records.",
    privacyQuestion: "What is visible publicly?", privacyAnswer: "Only the safe professional profile is exposed: identity, credentials summary, practice location, consultation modes, reviews and professional information. Private patient data and documents remain behind authentication.",
    doctor: "Doctor", reviews: "reviews", online: "online", offline: "in-clinic", homeVisit: "home visit", patient: "MediCore patient",
    yearsExperience: "{{count}} years experience", reviewCount: "{{count}} reviews", specialtyDoctors: "{{count}} verified doctors", averageRating: "{{rating}} average rating", verifiedPatientExperience: "Verified patient experience", patientExperienceFallback: "A patient experience shared through MediCore.", consultedDoctor: "Consulted {{name}}",
    journey: { discover: "Discover", discoverText: "Find by specialty, location, mode and availability.", verify: "Verify", verifyText: "Review credentials, experience, reviews and practice details.", book: "Book", bookText: "Request a real slot from the doctor schedule.", consult: "Consult", consultText: "Continue into the appointment and clinical workflow.", continue: "Continue", continueText: "Follow-up, reviews and care history stay connected." },
    trustCards: {
      verifiedIdentity: "Verified identity", verifiedIdentityText: "Approved doctor profiles only",
      realScheduling: "Real scheduling", realSchedulingText: "Availability from the booking engine",
      consultationReviews: "Consultation reviews", consultationReviewsText: "Linked to completed care",
      privateRecords: "Private records", privateRecordsText: "Clinical data stays protected",
      paymentExpectations: "Payment expectations are visible", paymentExpectationsText: "Currency, taxes, booking window and refund configuration come from hospital settings.",
      professionalDepth: "Professional depth", professionalDepthText: "Education, experience, awards, publications, clinics and languages can strengthen a profile without exposing private records.",
      boundedIntelligence: "Intelligence stays bounded", boundedIntelligenceText: "Decision-support shortcuts help patients navigate specialties but never claim to diagnose symptoms."
    }
  },
  search: { highestRated: "Highest rated", mostExperienced: "Most experienced", lowestFees: "Lowest fees", highestFees: "Highest fees", mostReviewed: "Most reviewed", recentlyVerified: "Recently verified", removeSaved: "Remove from saved doctors", saveDoctor: "Save doctor", yearsShort: "yrs", pageOf: "Page {{page}} of {{pages}}" },
  profile: { online: "Online", offline: "In-clinic", homeVisit: "Home visit", doctorUnavailable: "Doctor unavailable", rating: "Rating", reviews: "Reviews", consultations: "Consultations", years: "Years", primaryPractice: "Primary practice", locationNotSpecified: "Location not specified", patientReviews: "Patient reviews · {{count}}", basedOnReviews: "Based on {{count}} public reviews", loading: "Loading…", next: "Next", languages: "Languages", insurance: "Insurance listed", emergency: "Emergency", medicalCouncil: "Medical council", present: "Present", minutes: "min", days: { monday: "Monday", tuesday: "Tuesday", wednesday: "Wednesday", thursday: "Thursday", friday: "Friday", saturday: "Saturday", sunday: "Sunday" }, yes: "Yes", no: "No", bookingWindow: "Booking window: up to {{days}} days, subject to availability.", currencyTax: "Currency: {{currency}}; configured tax rate: {{taxRate}}%." },
  compare: { specialization: "Specialization", qualification: "Qualification", experience: "Experience", years: "{{count}} years", practiceLocation: "Practice location", hospitalClinic: "Hospital / clinic", languages: "Languages", consultationModes: "Consultation modes", consultationFee: "Consultation fee", rating: "Rating", ratingValue: "{{value}} / 5", reviews: "Reviews", completedConsultations: "Completed consultations", notAvailable: "—" },
  contact: { email: "Email", phone: "Phone", timezone: "Operating timezone", notConfigured: "Not configured publicly" },
  about: { discover: "Discover", discoverText: "Doctor search, specialty browsing, location filters and decision-support navigation.", trust: "Trust", trustDescription: "Verification state, professional credentials, reviews and practice context before the booking decision.", coordinate: "Coordinate", coordinateText: "Availability and appointment requests connect to the same workflow.", care: "Care", careText: "Consultations and supported clinical workflows continue behind the public boundary.", continuity: "Continuity", continuityDescription: "Follow-up scheduling and patient workflows continue after the consultation.", patient1: "Compare doctors before booking", patient2: "See verified professional information", patient3: "Filter by real availability", patient4: "Understand fees and refund expectations", patient5: "Continue into patient records", patient6: "Keep follow-up history connected", platform1: "Professional profile depth", platform2: "Verification and compliance state", platform3: "Public reputation and reviews", platform4: "Availability and booking", platform5: "Practice and patient workflows", platform6: "Follow-up continuity after consultation", trustTitle: "Trust before conversion", trustText: "Verification, review history, professional details and availability appear before a patient is asked to book.", sourceTitle: "One source of truth", sourceText: "Public discovery reads the same doctor, appointment, review and hospital configuration data that drives internal workflows.", continuityTitle: "Continuity after the click", continuityText: "The public journey connects to supported appointment, consultation and follow-up workflows." },
  services: { price: "Price", explore: "Explore service", published: "Published", noServices: "No services are currently available for public discovery.", count: "{{count}} services ready to explore" },
  articles: { published: "Published", count: "articles", read: "Read article", noArticles: "No published articles match your search." },
  articleDetail: { published: "Published" }
};
