const p17 = {
  contact: {
    eyebrow: "Contact MediCore", title: "We're here to help", accent: " with your enquiry.",
    intro: "For healthcare support, partnerships, technical questions, billing questions, or general enquiries, send a message through the form below.",
    channels: "Contact channels", support: "General support", notConfigured: "Not configured", timezone: "Service timezone",
    formEyebrow: "Send an enquiry", formTitle: "Tell us how we can help",
    name: "Full name", email: "Email address", phone: "Phone number", optional: " (optional)", inquiry: "Inquiry type", subject: "Subject", message: "Message", preferred: "Preferred contact method", consent: "I agree that MediCore may use the information submitted here to respond to my enquiry.", submit: "Submit enquiry", submitting: "Submitting…", success: "Your enquiry has been submitted successfully.", reference: "Reference ID", copy: "Copy reference", copied: "Reference copied", error: "We could not submit your enquiry. Please try again.", privacy: "Privacy Policy", dataRights: "Data Rights", terms: "Terms of Service", sensitiveTitle: "Please keep sensitive information out of this form", sensitive: "Do not submit passwords, payment credentials, highly sensitive medical information, or other confidential information through this contact form.", duplicate: "This enquiry was already received recently. Your existing reference is shown below.", invalid: "Please correct the highlighted fields.", network: "We could not reach MediCore. Check your connection and try again.", types: { general: "General enquiry", patient_support: "Patient support", doctor_support: "Doctor/provider support", hospital_partnership: "Hospital/clinic partnership", business: "Business enquiry", technical: "Technical support", billing: "Billing/payment enquiry", privacy_data_rights: "Privacy/data rights", other: "Other" }, methods: { email: "Email", phone: "Phone", either: "Email or phone" }, privacyRedirect: "For a privacy or data-rights request, use the Data Rights Center instead of sending sensitive details here.", required: "Required",
  },
  adminLeads: {
    title: "Lead Management", description: "Review, assign and resolve real enquiries submitted through MediCore.", search: "Search reference, name, email, phone or subject", status: "Status", priority: "Priority", inquiry: "Inquiry type", all: "All", loading: "Loading leads…", retry: "Try again", empty: "No enquiries found", detail: "Lead detail", contact: "Contact information", enquiry: "Enquiry", management: "Management", timeline: "Timeline", assign: "Assign", priorityLabel: "Priority", statusLabel: "Status", note: "Internal note", addNote: "Add note", save: "Save", noNotes: "No internal notes yet.", noTimeline: "No timeline events yet.", unauthorized: "You do not have permission to manage leads.", error: "Lead operation failed. Please try again.", created: "Lead created", assigned: "Lead assigned", priorityChanged: "Priority changed", statusChanged: "Status changed", noteAdded: "Internal note added", resolved: "Lead resolved", closed: "Lead closed", statuses: { new: "New", acknowledged: "Acknowledged", in_progress: "In progress", waiting_for_user: "Waiting for user", resolved: "Resolved", closed: "Closed" }, priorities: { low: "Low", medium: "Medium", high: "High", urgent: "Urgent" }, types: { general: "General enquiry", patient_support: "Patient support", doctor_support: "Doctor/provider support", hospital_partnership: "Hospital/clinic partnership", business: "Business enquiry", technical: "Technical support", billing: "Billing/payment enquiry", privacy_data_rights: "Privacy/data rights", other: "Other" }, assignedTo: "Assigned to", unassigned: "Unassigned", updatePriority: "Update priority", updateStatus: "Update status", date: "Created", notification: "Acknowledgement email", delivered: "Delivered", failed: "Failed", skipped: "Not sent", none: "Not attempted", reference: "Reference ID"
  }
};
export default p17;
